# Generated by Django 6.0.4 on 2026-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(max_length=200, verbose_name='متن'),
        ),
    ]
