# Generated by Django 5.2.16 on 2026-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_announcement_link_alter_announcement_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="زیرعنوان"
                    ),
                ),
                ("image", models.ImageField(upload_to="hero/", verbose_name="تصویر")),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        default="خرید کنید",
                        max_length=50,
                        verbose_name="متن دکمه",
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True,
                        default="/shop/",
                        max_length=200,
                        verbose_name="لینک دکمه",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "اسلاید بنر",
                "verbose_name_plural": "اسلایدهای بنر",
                "ordering": ("order",),
            },
        ),
    ]
