# Generated by Django 5.2.16 on 2026-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_heroslide"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeCategoryCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="عنوان")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        default="/shop/", max_length=200, verbose_name="لینک"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home-cards/",
                        verbose_name="تصویر (اختیاری — جای آیکون)",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        default="lni lni-tshirt",
                        max_length=50,
                        verbose_name="کلاس آیکون (اگر تصویر ندارید)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#00B8CC",
                        max_length=20,
                        verbose_name="رنگ آیکون/پس\u200cزمینه",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "کارت دسته\u200cبندی صفحه اصلی",
                "verbose_name_plural": "کارت\u200cهای دسته\u200cبندی صفحه اصلی",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_watermark",
                    models.CharField(
                        default="ORAM SHOP",
                        max_length=60,
                        verbose_name="متن واترمارک صفحه اصلی",
                    ),
                ),
                (
                    "topbar_style",
                    models.CharField(
                        choices=[
                            ("black", "مشکی ساده"),
                            ("charcoal", "شارکول"),
                            ("gradient-cyan", "گرادینت مشکی → سایان"),
                            ("gradient-dark", "گرادینت سرمه\u200cای تیره"),
                            ("ivory", "کرم روشن (متن تیره)"),
                        ],
                        default="black",
                        max_length=20,
                        verbose_name="رنگ نوار اطلاعیه بالای سایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
    ]
