# Generated by Django 5.2.16 on 2026-07-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_homecategorycard_sitesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="topbar_style",
            field=models.CharField(
                choices=[
                    ("black", "مشکی ساده"),
                    ("charcoal", "شارکول (خاکستری تیره)"),
                    ("navy", "سرمه\u200cای"),
                    ("ivory", "کرم روشن (متن تیره)"),
                    ("gradient-cyan", "گرادینت مشکی → سایان"),
                    ("gradient-dark", "گرادینت آبی نفتی"),
                    ("gradient-purple", "گرادینت بنفش"),
                    ("gradient-sunset", "گرادینت غروب (قرمز)"),
                    ("gradient-emerald", "گرادینت زمردی (سبز)"),
                ],
                default="black",
                max_length=20,
                verbose_name="رنگ نوار اطلاعیه بالای سایت",
            ),
        ),
    ]
