# Generated by Django 5.2.16 on 2026-07-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_sitesetting_topbar_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="credit_text",
            field=models.CharField(
                blank=True,
                default="طراحی و توسعه توسط گروه ساتک کدینگ",
                max_length=120,
                verbose_name="متن سازندهٔ سایت",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="credit_url",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="لینک سازنده"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_about",
            field=models.TextField(
                blank=True,
                default="اُرام\u200cشاپ، فروشگاه اینترنتی پوشاک مردانه و زنانه؛ با ضمانت اصالت کالا، ارسال سریع به سراسر ایران و ۷ روز ضمانت بازگشت.",
                verbose_name="متن دربارهٔ فوتر",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_address",
            field=models.CharField(blank=True, max_length=200, verbose_name="آدرس"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_email",
            field=models.CharField(
                blank=True,
                default="info@oramshop.com",
                max_length=80,
                verbose_name="ایمیل",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_hours",
            field=models.CharField(
                blank=True,
                default="شنبه تا پنجشنبه، ۹ تا ۱۸",
                max_length=80,
                verbose_name="ساعات کاری",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_phone",
            field=models.CharField(
                blank=True,
                default="۰۲۱-۰۰۰۰۰۰۰۰",
                max_length=40,
                verbose_name="تلفن پشتیبانی",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="instagram_url",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="لینک اینستاگرام"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="shop_banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="banners/",
                verbose_name="بنر صفحه محصولات",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="shop_banner_subtitle",
            field=models.CharField(
                blank=True,
                default="جدیدترین کالکشن\u200cها با بهترین قیمت",
                max_length=160,
                verbose_name="زیرعنوان بنر محصولات",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="shop_banner_title",
            field=models.CharField(
                blank=True,
                default="فروشگاه اُرام\u200cشاپ",
                max_length=100,
                verbose_name="عنوان بنر محصولات",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="telegram_url",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="لینک تلگرام"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="whatsapp_url",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="لینک واتساپ"
            ),
        ),
    ]
