# Generated by Django 5.2.16 on 2026-07-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sitesetting_credit_text_sitesetting_credit_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="search_keyword",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="کلمهٔ کلیدی رتبه"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="search_rank",
            field=models.PositiveIntegerField(
                default=0,
                help_text="این عدد را از گوگل سرچ\u200cکنسول وارد کنید (۰ یعنی نامشخص). اگر ۱ تا ۱۰ باشد، در داشبورد آلرت داده می\u200cشود.",
                verbose_name="رتبهٔ فعلی در جستجوی گوگل",
            ),
        ),
    ]
