# Generated by Django 5.2.16 on 2026-07-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sitesetting_search_keyword_sitesetting_search_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                (
                    "recipients_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد گیرندگان"
                    ),
                ),
            ],
            options={
                "verbose_name": "کمپین خبرنامه",
                "verbose_name_plural": "کمپین\u200cهای خبرنامه",
                "ordering": ("-sent_at",),
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="ایمیل"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
            ],
            options={
                "verbose_name": "مشترک خبرنامه",
                "verbose_name_plural": "مشترکین خبرنامه",
                "ordering": ("-created_at",),
            },
        ),
    ]
