# Generated by Django 5.2.16 on 2026-07-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_newslettercampaign_newslettersubscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=15, null=True, unique=True, verbose_name="موبایل"
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="ایمیل"
            ),
        ),
    ]
