# Generated by Django 5.2.16 on 2026-07-12 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_newslettersubscriber_mobile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        verbose_name="کلید نشست",
                    ),
                ),
                (
                    "path",
                    models.CharField(blank=True, max_length=255, verbose_name="مسیر"),
                ),
                (
                    "ip_hash",
                    models.CharField(blank=True, max_length=32, verbose_name="هش IP"),
                ),
                (
                    "is_authenticated",
                    models.BooleanField(default=False, verbose_name="کاربر عضو"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان بازدید"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید سایت",
                "verbose_name_plural": "بازدیدهای سایت",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["created_at", "session_key"],
                        name="core_sitevi_created_f07693_idx",
                    )
                ],
            },
        ),
    ]
