# Generated by Django 5.2.16 on 2026-07-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_sitevisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="about_home",
            field=models.TextField(
                blank=True,
                default="اُرام\u200cشاپ با هدف ارائهٔ پوشاک باکیفیت مردانه و زنانه از برندهای معتبر راه\u200cاندازی شده است. ما با ضمانت اصالت کالا، ارسال سریع به سراسر ایران، ۷ روز ضمانت بازگشت و پشتیبانی پاسخگو تلاش می\u200cکنیم تجربه\u200cای آرام و مطمئن از خرید آنلاین برای شما بسازیم.",
                verbose_name="متن دربارهٔ ما (قبل از فوتر)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="men_vector",
            field=models.ImageField(
                blank=True,
                help_text="اگر خالی باشد وکتور پیش\u200cفرض نمایش داده می\u200cشود",
                null=True,
                upload_to="collections/",
                verbose_name="وکتور کالکشن مردانه",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="women_vector",
            field=models.ImageField(
                blank=True,
                help_text="اگر خالی باشد وکتور پیش\u200cفرض نمایش داده می\u200cشود",
                null=True,
                upload_to="collections/",
                verbose_name="وکتور کالکشن زنانه",
            ),
        ),
    ]
