# Generated by Django 5.2.16 on 2026-07-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_sitesetting_about_home_sitesetting_men_vector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="bot_api_key_override",
            field=models.CharField(
                blank=True,
                help_text="اگر خالی باشد مقدار BOT_API_KEY از .env استفاده می\u200cشود",
                max_length=128,
                verbose_name="کلید API ربات تلگرام",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="goftino_id_override",
            field=models.CharField(
                blank=True,
                help_text="اگر خالی باشد مقدار GOFTINO_ID از .env استفاده می\u200cشود",
                max_length=16,
                verbose_name="کد ویجت گفتینو",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="men_collection_color",
            field=models.CharField(
                blank=True,
                default="#2c5364",
                help_text="رنگ انتهای گرادینت بنر کالکشن مردانه در صفحه اصلی",
                max_length=20,
                verbose_name="رنگ کالکشن مردانه",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="women_collection_color",
            field=models.CharField(
                blank=True,
                default="#7a4a63",
                help_text="رنگ انتهای گرادینت بنر کالکشن زنانه در صفحه اصلی",
                max_length=20,
                verbose_name="رنگ کالکشن زنانه",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="zarinpal_merchant_id",
            field=models.CharField(
                blank=True,
                help_text="اگر خالی باشد مقدار ZARINPAL_MERCHANT_ID از .env استفاده می\u200cشود",
                max_length=64,
                verbose_name="مرچنت\u200cکد زرین\u200cپال",
            ),
        ),
    ]
