# Generated by Django 5.2.16 on 2026-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_sitesetting_bot_api_key_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="global_alert",
            field=models.TextField(
                blank=True,
                default="",
                help_text="در بالای همهٔ صفحات نمایش داده می\u200cشود و کاربر نمی\u200cتواند آن را ببندد — خالی = مخفی",
                verbose_name="پیام سراسری سایت",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="global_alert_style",
            field=models.CharField(
                choices=[
                    ("info", "اطلاع\u200cرسانی (سایان)"),
                    ("warning", "هشدار (نارنجی)"),
                    ("danger", "مهم/بحرانی (قرمز)"),
                ],
                default="info",
                max_length=10,
                verbose_name="رنگ پیام سراسری",
            ),
        ),
    ]
