# Generated by Django 5.2.16 on 2026-07-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_sitesetting_global_alert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="enamad_image",
            field=models.ImageField(
                blank=True,
                help_text="تصویر نماد را از پنل enamad.ir دانلود و اینجا آپلود کنید",
                null=True,
                upload_to="badges/",
                verbose_name="تصویر نماد اعتماد (ای\u200cنماد)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="enamad_link",
            field=models.CharField(
                blank=True,
                help_text="لینک صفحه تأیید (trustseal.enamad.ir/...) از پنل ای\u200cنماد",
                max_length=500,
                verbose_name="لینک نماد اعتماد",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="zarinpal_badge_image",
            field=models.ImageField(
                blank=True,
                help_text="لوگوی اعتماد زرین\u200cپال را از پنل زرین\u200cپال بگیرید",
                null=True,
                upload_to="badges/",
                verbose_name="تصویر نماد زرین\u200cپال",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="zarinpal_badge_link",
            field=models.CharField(
                blank=True,
                help_text="لینک صفحه تأیید درگاه شما در zarinpal.com",
                max_length=500,
                verbose_name="لینک نماد زرین\u200cپال",
            ),
        ),
    ]
