# Generated by Django 5.2.16 on 2026-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_sitesetting_enamad_image_sitesetting_enamad_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="feature_blog",
            field=models.BooleanField(
                default=True,
                help_text="خاموش: لینک\u200cهای بلاگ حذف و صفحات بلاگ ۴۰۴ می\u200cشوند",
                verbose_name="بلاگ فعال باشد",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="feature_newsletter",
            field=models.BooleanField(
                default=True,
                help_text="خاموش: فرم عضویت خبرنامه در فوتر مخفی می\u200cشود",
                verbose_name="خبرنامه فعال باشد",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="feature_reviews",
            field=models.BooleanField(
                default=True,
                help_text="خاموش: بخش نظرات و فرم ثبت نظر در صفحه محصول مخفی می\u200cشود",
                verbose_name="نظرات محصول فعال باشد",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="feature_wholesale",
            field=models.BooleanField(
                default=True,
                help_text="خاموش: منوی محصولات عمده، نوار صفحه اصلی و فیلتر عمده مخفی می\u200cشوند",
                verbose_name="بخش عمده\u200cفروشی فعال باشد",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="feature_wishlist",
            field=models.BooleanField(
                default=True,
                help_text="خاموش: قلب\u200cها، منوی علاقه\u200cمندی و صفحه آن مخفی می\u200cشوند",
                verbose_name="علاقه\u200cمندی\u200cها فعال باشد",
            ),
        ),
    ]
