# Generated by Django 5.2.16 on 2026-07-19 02:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_sitesetting_feature_blog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان صفحه")),
                (
                    "slug",
                    models.SlugField(
                        max_length=140,
                        unique=True,
                        verbose_name="اسلاگ (نام انگلیسی در URL)",
                    ),
                ),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="متن صفحه"),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(default=True, verbose_name="نمایش در فوتر"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "صفحه ثابت",
                "verbose_name_plural": "صفحات ثابت",
                "ordering": ("order", "title"),
            },
        ),
    ]
