# Generated by Django 5.2.16 on 2026-07-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_seed_static_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "contact",
                    models.CharField(
                        max_length=120, verbose_name="ایمیل یا شماره تماس"
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=150, verbose_name="موضوع"),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ("-created_at",),
            },
        ),
    ]
