# Generated by Django 5.2.16 on 2026-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="enamad_code",
            field=models.TextField(
                blank=True,
                help_text="کل کد <a><img></a> که پنل ای\u200cنماد می\u200cدهد را اینجا پیست کنید. لوگو فقط روی دامنهٔ تأییدشده نمایش داده می\u200cشود.",
                verbose_name="کد کامل نماد اعتماد (ای\u200cنماد)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="enamad_image",
            field=models.ImageField(
                blank=True,
                help_text="اگر کد کامل بالا را دارید، این را خالی بگذارید",
                null=True,
                upload_to="badges/",
                verbose_name="تصویر نماد اعتماد (اگر کد کامل ندارید)",
            ),
        ),
    ]
