# Generated by Django 5.2.16 on 2026-07-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_wholesale",
            field=models.BooleanField(
                default=False,
                help_text="فقط مشتریان تأییدشده قیمت محصولات عمده را می\u200cبینند",
                verbose_name="مشتری عمده (تأییدشده)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="wholesale_requested",
            field=models.BooleanField(default=False, verbose_name="درخواست حساب عمده"),
        ),
    ]
