# Generated by Django 5.2.16 on 2026-07-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_wholesale_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("otp", "کد تأیید"),
                            ("order", "وضعیت سفارش"),
                            ("newsletter", "خبرنامه"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=12,
                        verbose_name="نوع پیامک",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="موبایل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "موفق"), ("error", "ناموفق")],
                        default="ok",
                        max_length=6,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="کد پاسخ sms.ir"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="پیام / خطا"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان"
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ پیامک",
                "verbose_name_plural": "لاگ\u200cهای پیامک",
                "ordering": ("-created_at",),
            },
        ),
    ]
