# Generated by Django 6.0.4 on 2026-07-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.CharField(blank=True, choices=[('top', 'بالاتنه'), ('bottom', 'پایین\u200cتنه')], max_length=10, verbose_name='نوع اندام'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='کد محصول (SKU)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(help_text='مثال: #FF5733', max_length=7, verbose_name='کد رنگ'),
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoulder', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='عرض شانه (cm)')),
                ('sleeve', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='طول آستین (cm)')),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='عرض سینه (cm)')),
                ('length_top', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='قد (cm)')),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='عرض کمر (cm)')),
                ('hip', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='عرض ران (cm)')),
                ('crotch', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='فاق (cm)')),
                ('length_bottom', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='قد (cm)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_charts', to='catalog.product', verbose_name='محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='catalog.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'جدول سایزبندی',
                'verbose_name_plural': 'جداول سایزبندی',
                'unique_together': {('product', 'size')},
            },
        ),
    ]
