# Generated by Django 6.0.4 on 2026-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_category_type_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='کد محصول (SKU)'),
        ),
    ]
