# Generated by Django 5.2.16 on 2026-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_sku"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name": "سایز",
                "verbose_name_plural": "سایزها",
            },
        ),
        migrations.AddField(
            model_name="size",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="کوچک به بزرگ؛ برای سایز عددی خودکار پر می\u200cشود",
                verbose_name="ترتیب نمایش",
            ),
        ),
        migrations.AddField(
            model_name="sizechart",
            name="foot_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="طول کف پا (cm)",
            ),
        ),
    ]
