# Generated by Django 5.2.16 on 2026-07-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_size_options_size_sort_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_wholesale",
            field=models.BooleanField(
                default=False,
                help_text="قیمت فقط برای مشتریان عمدهٔ تأییدشده نمایش داده می\u200cشود",
                verbose_name="محصول عمده",
            ),
        ),
    ]
